/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.qualifier.model.impl;

import com.liferay.commerce.qualifier.model.CommerceDefaultSetting;
import com.liferay.commerce.qualifier.model.CommerceDefaultSettingModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceDefaultSetting service. Represents a row in the &quot;CommerceDefaultSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommerceDefaultSettingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceDefaultSettingImpl}.
 * </p>
 *
 * @author Riccardo Alberti
 * @see CommerceDefaultSettingImpl
 * @generated
 */
@JSON(strict = true)
public class CommerceDefaultSettingModelImpl
	extends BaseModelImpl<CommerceDefaultSetting>
	implements CommerceDefaultSettingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce default setting model instance should use the <code>CommerceDefaultSetting</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommerceDefaultSetting";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"commerceDefaultSettingId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceDefaultSettingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommerceDefaultSetting (mvccVersion LONG default 0 not null,commerceDefaultSettingId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table CommerceDefaultSetting";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceDefaultSetting.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommerceDefaultSetting.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommerceDefaultSettingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceDefaultSettingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceDefaultSettingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceDefaultSettingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceDefaultSetting.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceDefaultSetting.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceDefaultSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommerceDefaultSetting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceDefaultSetting, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommerceDefaultSetting)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceDefaultSetting, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceDefaultSetting, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceDefaultSetting)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceDefaultSetting, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceDefaultSetting, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CommerceDefaultSetting, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CommerceDefaultSetting, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommerceDefaultSetting, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CommerceDefaultSetting, Object>>();
		Map<String, BiConsumer<CommerceDefaultSetting, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CommerceDefaultSetting, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", CommerceDefaultSetting::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<CommerceDefaultSetting, Long>)
				CommerceDefaultSetting::setMvccVersion);
		attributeGetterFunctions.put(
			"commerceDefaultSettingId",
			CommerceDefaultSetting::getCommerceDefaultSettingId);
		attributeSetterBiConsumers.put(
			"commerceDefaultSettingId",
			(BiConsumer<CommerceDefaultSetting, Long>)
				CommerceDefaultSetting::setCommerceDefaultSettingId);
		attributeGetterFunctions.put(
			"companyId", CommerceDefaultSetting::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CommerceDefaultSetting, Long>)
				CommerceDefaultSetting::setCompanyId);
		attributeGetterFunctions.put(
			"userId", CommerceDefaultSetting::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CommerceDefaultSetting, Long>)
				CommerceDefaultSetting::setUserId);
		attributeGetterFunctions.put(
			"userName", CommerceDefaultSetting::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<CommerceDefaultSetting, String>)
				CommerceDefaultSetting::setUserName);
		attributeGetterFunctions.put(
			"createDate", CommerceDefaultSetting::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CommerceDefaultSetting, Date>)
				CommerceDefaultSetting::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", CommerceDefaultSetting::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CommerceDefaultSetting, Date>)
				CommerceDefaultSetting::setModifiedDate);
		attributeGetterFunctions.put("name", CommerceDefaultSetting::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<CommerceDefaultSetting, String>)
				CommerceDefaultSetting::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCommerceDefaultSettingId() {
		return _commerceDefaultSettingId;
	}

	@Override
	public void setCommerceDefaultSettingId(long commerceDefaultSettingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceDefaultSettingId = commerceDefaultSettingId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceDefaultSetting.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceDefaultSetting toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommerceDefaultSetting>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceDefaultSettingImpl commerceDefaultSettingImpl =
			new CommerceDefaultSettingImpl();

		commerceDefaultSettingImpl.setMvccVersion(getMvccVersion());
		commerceDefaultSettingImpl.setCommerceDefaultSettingId(
			getCommerceDefaultSettingId());
		commerceDefaultSettingImpl.setCompanyId(getCompanyId());
		commerceDefaultSettingImpl.setUserId(getUserId());
		commerceDefaultSettingImpl.setUserName(getUserName());
		commerceDefaultSettingImpl.setCreateDate(getCreateDate());
		commerceDefaultSettingImpl.setModifiedDate(getModifiedDate());
		commerceDefaultSettingImpl.setName(getName());

		commerceDefaultSettingImpl.resetOriginalValues();

		return commerceDefaultSettingImpl;
	}

	@Override
	public CommerceDefaultSetting cloneWithOriginalValues() {
		CommerceDefaultSettingImpl commerceDefaultSettingImpl =
			new CommerceDefaultSettingImpl();

		commerceDefaultSettingImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		commerceDefaultSettingImpl.setCommerceDefaultSettingId(
			this.<Long>getColumnOriginalValue("commerceDefaultSettingId"));
		commerceDefaultSettingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		commerceDefaultSettingImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		commerceDefaultSettingImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		commerceDefaultSettingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		commerceDefaultSettingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		commerceDefaultSettingImpl.setName(
			this.<String>getColumnOriginalValue("name"));

		return commerceDefaultSettingImpl;
	}

	@Override
	public int compareTo(CommerceDefaultSetting commerceDefaultSetting) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), commerceDefaultSetting.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommerceDefaultSetting)) {
			return false;
		}

		CommerceDefaultSetting commerceDefaultSetting =
			(CommerceDefaultSetting)object;

		long primaryKey = commerceDefaultSetting.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceDefaultSetting> toCacheModel() {
		CommerceDefaultSettingCacheModel commerceDefaultSettingCacheModel =
			new CommerceDefaultSettingCacheModel();

		commerceDefaultSettingCacheModel.mvccVersion = getMvccVersion();

		commerceDefaultSettingCacheModel.commerceDefaultSettingId =
			getCommerceDefaultSettingId();

		commerceDefaultSettingCacheModel.companyId = getCompanyId();

		commerceDefaultSettingCacheModel.userId = getUserId();

		commerceDefaultSettingCacheModel.userName = getUserName();

		String userName = commerceDefaultSettingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceDefaultSettingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceDefaultSettingCacheModel.createDate = createDate.getTime();
		}
		else {
			commerceDefaultSettingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceDefaultSettingCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commerceDefaultSettingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commerceDefaultSettingCacheModel.name = getName();

		String name = commerceDefaultSettingCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			commerceDefaultSettingCacheModel.name = null;
		}

		return commerceDefaultSettingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceDefaultSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommerceDefaultSetting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceDefaultSetting, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CommerceDefaultSetting)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommerceDefaultSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommerceDefaultSetting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceDefaultSetting, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((CommerceDefaultSetting)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CommerceDefaultSetting>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CommerceDefaultSetting.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _commerceDefaultSettingId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<CommerceDefaultSetting, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CommerceDefaultSetting)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"commerceDefaultSettingId", _commerceDefaultSettingId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("commerceDefaultSettingId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("name", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CommerceDefaultSetting _escapedModel;

}