/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.qualifier.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommerceDefaultSetting service. Represents a row in the &quot;CommerceDefaultSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.qualifier.model.impl.CommerceDefaultSettingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.qualifier.model.impl.CommerceDefaultSettingImpl</code>.
 * </p>
 *
 * @author Riccardo Alberti
 * @see CommerceDefaultSetting
 * @generated
 */
@ProviderType
public interface CommerceDefaultSettingModel
	extends AuditedModel, BaseModel<CommerceDefaultSetting>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce default setting model instance should use the {@link CommerceDefaultSetting} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce default setting.
	 *
	 * @return the primary key of this commerce default setting
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce default setting.
	 *
	 * @param primaryKey the primary key of this commerce default setting
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this commerce default setting.
	 *
	 * @return the mvcc version of this commerce default setting
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this commerce default setting.
	 *
	 * @param mvccVersion the mvcc version of this commerce default setting
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the commerce default setting ID of this commerce default setting.
	 *
	 * @return the commerce default setting ID of this commerce default setting
	 */
	public long getCommerceDefaultSettingId();

	/**
	 * Sets the commerce default setting ID of this commerce default setting.
	 *
	 * @param commerceDefaultSettingId the commerce default setting ID of this commerce default setting
	 */
	public void setCommerceDefaultSettingId(long commerceDefaultSettingId);

	/**
	 * Returns the company ID of this commerce default setting.
	 *
	 * @return the company ID of this commerce default setting
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce default setting.
	 *
	 * @param companyId the company ID of this commerce default setting
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce default setting.
	 *
	 * @return the user ID of this commerce default setting
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce default setting.
	 *
	 * @param userId the user ID of this commerce default setting
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce default setting.
	 *
	 * @return the user uuid of this commerce default setting
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce default setting.
	 *
	 * @param userUuid the user uuid of this commerce default setting
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce default setting.
	 *
	 * @return the user name of this commerce default setting
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce default setting.
	 *
	 * @param userName the user name of this commerce default setting
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce default setting.
	 *
	 * @return the create date of this commerce default setting
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce default setting.
	 *
	 * @param createDate the create date of this commerce default setting
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce default setting.
	 *
	 * @return the modified date of this commerce default setting
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce default setting.
	 *
	 * @param modifiedDate the modified date of this commerce default setting
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this commerce default setting.
	 *
	 * @return the name of this commerce default setting
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this commerce default setting.
	 *
	 * @param name the name of this commerce default setting
	 */
	public void setName(String name);

	/**
	 * Returns the parameter settings of this commerce default setting.
	 *
	 * @return the parameter settings of this commerce default setting
	 */
	@AutoEscape
	public String getParameterSettings();

	/**
	 * Sets the parameter settings of this commerce default setting.
	 *
	 * @param parameterSettings the parameter settings of this commerce default setting
	 */
	public void setParameterSettings(String parameterSettings);

	@Override
	public CommerceDefaultSetting cloneWithOriginalValues();

}