/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export const applicationExternalReferenceCodes = {
	OAUTH_AGENT_EXTERNAL_REFERENCE_CODE:
		'liferay-universal-connector-oauth-application-user-agent',
	OAUTH_SERVER_EXTERNAL_REFERENCE_CODE:
		'liferay-universal-connector-oauth-application-server',
};

export const applicationSpecificConfigKeys = {
	PROXY_OBJECTS_CACHE_DURATION: 'PROXY_OBJECTS_CACHE_DURATION',
	PROXY_OBJECTS_END_POINT: 'PROXY_OBJECTS_END_POINT',
};

export const environmentConfigKeys = {
	COM_LIFERAY_LXC_DXP_DOMAINS: 'COM_LIFERAY_LXC_DXP_DOMAINS',
	COM_LIFERAY_LXC_DXP_MAIN_DOMAIN: 'COM_LIFERAY_LXC_DXP_MAIN_DOMAIN',
	COM_LIFERAY_LXC_DXP_SERVER_PROTOCOL: 'COM_LIFERAY_LXC_DXP_SERVER_PROTOCOL',
	LIFERAY_OAUTH_APPLICATION_EXTERNAL_REFERENCE_CODES:
		'LIFERAY_OAUTH_APPLICATION_EXTERNAL_REFERENCE_CODES',
};

export const serviceConfigKeys = {
	READY_PATH: 'READY_PATH',
	SERVER_PORT: 'SERVER_PORT',
};

export const oauthAgentConfigKeys = {
	_OAUTH2_AUTHORIZATION_URI: '_OAUTH2_AUTHORIZATION_URI',
	_OAUTH2_INTROSPECTION_URI: '_OAUTH2_INTROSPECTION_URI',
	_OAUTH2_JWKS_URI: '_OAUTH2_JWKS_URI',
	_OAUTH2_REDIRECT_URIS: '_OAUTH2_REDIRECT_URIS',
	_OAUTH2_TOKEN_URI: '_OAUTH2_TOKEN_URI',
	_OAUTH2_USER_AGENT_AUDIENCE: '_OAUTH2_USER_AGENT_AUDIENCE',
	_OAUTH2_USER_AGENT_CLIENT_ID: '_OAUTH2_USER_AGENT_CLIENT_ID',
	_OAUTH2_USER_AGENT_SCOPES: '_OAUTH2_USER_AGENT_SCOPES',
};

export const oauthServerConfigKeys = {
	_OAUTH2_AUTHORIZATION_URI: '_OAUTH2_AUTHORIZATION_URI',
	_OAUTH2_HEADLESS_SERVER_AUDIENCE: '_OAUTH2_HEADLESS_SERVER_AUDIENCE',
	_OAUTH2_HEADLESS_SERVER_CLIENT_ID: '_OAUTH2_HEADLESS_SERVER_CLIENT_ID',
	_OAUTH2_HEADLESS_SERVER_CLIENT_SECRET:
		'_OAUTH2_HEADLESS_SERVER_CLIENT_SECRET',
	_OAUTH2_HEADLESS_SERVER_SCOPES: '_OAUTH2_HEADLESS_SERVER_SCOPES',
	_OAUTH2_INTROSPECTION_URI: '_OAUTH2_INTROSPECTION_URI',
	_OAUTH2_JWKS_URI: '_OAUTH2_JWKS_URI',
	_OAUTH2_TOKEN_URI: '_OAUTH2_TOKEN_URI',
};
